### ISSUE TITLE
Textfield's `setText` should probably set the text rather than merely append to it.

### ISSUE THREAD

**Issue by shviller** [tavuntu/gooi#17]
Calling `deleteBack` a bunch of times before calling `setText` sounds counterintuitive.

**Comment by gustavostuff** [comment]
Could you please clarify? The `TextField:deleteBack()` function is internally called in 2 places: `TextField:updateCursor()` and `TextField:typeCode()`

`TextField:setText()` is never called internally, the user chooses when to use it. I can't just set a lua string for text fields, since they need a more complex structure to work with (a table), is that what you mean?

**Comment by gustavostuff** [comment]
Never mind, I see what you mean, it should be fixed now!
