### ISSUE TITLE
How to use multitouch joysticks, buttons in android screen, and if gooi suport that

### ISSUE THREAD

**Issue by beginnerButsmart** [tavuntu/gooi#28]
ive been trying to make a game, and i start to use gooi for creating joysticks, texts and some buttons on the screen... so when i start moving the player in my game with the joystick i cannot touch other buttons on the screen simultaneous with the joystick. and you can tell me how i can do it? ur wiki and docs dont show anything about it, if you can help me will be usefull

**Comment by gustavostuff** [comment]
I'm not maintaining this anymore so I don't know if it still works. Look at `gooi.pressed()`, `gooi.moved()` and `gooi.released()` in [gooi.lua](https://github.com/tavuntu/gooi/blob/master/gooi/gooi.lua), you should be able to make it work using those.

So instead of:
```lua
function love.mousepressed(x, y, button)  gooi.pressed() end
function love.mousereleased(x, y, button) gooi.released() end
```
use
```lua
function love.touchpressed(id, x, y)  gooi.pressed(id, x, y) end
function love.touchmoved(id, x, y)    gooi.moved(id, x, y) end
function love.touchreleased(id, x, y) gooi.released(id, x, y) end
```

and don't forget to call `gooi.update(dt)` (just in case)

**Comment by beginnerButsmart** [comment]
sure bro, ill try it if dont work ill post here my code and you can see whats happening wrong, i know you abandoned updating gooi so... thank you at all @tavuntu

**Comment by beginnerButsmart** [comment]
it worked fine bro, thank you now ill return my game development at all with love2d
