### ISSUE TITLE
Groups are confusing.

### ISSUE THREAD

**Issue by trelemar** [tavuntu/gooi#4]
I don't understand how to use groups, I feel like I had it working for a short period of time then couldn't figure it out again.

Some examples of my issues:

If I go to create a component with the arguments as a table, if I include group as a parameter, the component never gets created?? Or maybe it's never drawn or updated. Not quite sure.
```
--This Works
jump = gooi.newButton({text = "J"})

--This Does Not
jump = gooi.newButton({text = "J", group = "ingame"})
jump.group = "ingame"
```
Are groups a private thing for the library it's self? Or am I misunderstanding something? The lack of documentation is very frustrating but this GUI library is the best I've found.

I'd really like to take advantage of `gooi.setGroupEnabled()` however I may just have to have certain components in a specific table and enable and disable them all over a for loop. `component:setEnabled()` is working just fine.

**Comment by gustavostuff** [comment]
Groups exist as part of the API, the following example shows how they work:
```lua
require "gooi"
function love.load()
	currentGroup = ""-- No group yet
	-- These buttons have no group specified:
	gooi.newButton("Show group 1", 10,  10):onRelease(function(c) currentGroup = "g1"; end)
	gooi.newButton("Show group 2", 140, 10):onRelease(function(c) currentGroup = "g2"; end)

	gooi.newCheck("Checkbox of group 'g1'", 100, 100):setGroup("g1")-- belongs to group g1
	gooi.newCheck("Checkbox of group 'g2'", 100, 130):setGroup("g2"):bg("#FF8800AA")-- to g2
end
function love.draw()
	gooi.draw()-- Draw the buttons with no group specified
	gooi.draw(currentGroup)-- Draw the other components with a group
end
function love.mousereleased(x, y, button) gooi.released() end
function love.mousepressed(x, y, button)  gooi.pressed() end
```

But please note, the group thing is for drawing operations, this means that if you don't draw a group, it doesn't mean the components won't work when clicked or something, that's why you should use setEnabled() or setGroupEnabled() in conjunction; gooi.setGroupEnabled("g1", false), for instance, should work to disable all the elements for the group 'g1'.

About the docs, you're actually right, I focused a lot on other things and forget those, I'll add another issue regarding that, thanks for the reminder :)

**Comment by trelemar** [comment]
Thank you for the elaborate explaination and example. Turns out I just had no idea what I was doing. I should have seen the `c:setGroup()` function in the components.lua file source. Everything makes sense now. Thanks!

**Comment by gustavostuff** [comment]
You're welcome, as a "workaround", you can use the examples in main.lua as documentation, in the meantime.
